pub struct Rarity {
    Accessories: ((u8, u8)),
    Aura: ((u8, u8)),
    Body: ((u8, u8)),
    Chest: ((u8, u8)),
    Eyes: ((u8, u8)),
    Hair: ((u8, u8)),
    Horns: ((u8, u8)),
    Mouth: ((u8, u8)),
    Spine: ((u8, u8)),
    Wings: ((u8, u8)),
    Ears: (u8, u8),
}

pub const BACKGROUND: (u8, u8) = (0, 9);
pub const RARITY: (u8, u8) = (0, 6);
pub const ELEMENTS_LIST: [Rarity; 7] = [
    Rarity {
        Accessories: (0, 0),
        Aura: (0, 0),
        Body: (0, 9),
        Chest: (0, 0),
        Eyes: (0, 9),
        Hair: (0, 0),
        Horns: (0, 9),
        Mouth: (0, 9),
        Spine: (0, 0),
        Wings: (0, 0),
        Ears: (0, 0),
    },
    Rarity {
        Accessories: (0, 0),
        Aura: (0, 0),
        Body: (0, 5),
        Chest: (0, 0),
        Eyes: (0, 5),
        Hair: (0, 0),
        Horns: (0, 5),
        Mouth: (0, 5),
        Spine: (0, 6),
        Wings: (0, 0),
        Ears: (0, 0),
    },
    Rarity {
        Accessories: (0, 0),
        Aura: (0, 0),
        Body: (0, 3),
        Chest: (0, 4),
        Eyes: (0, 3),
        Hair: (0, 0),
        Horns: (0, 3),
        Mouth: (0, 3),
        Spine: (0, 4),
        Wings: (0, 0),
        Ears: (0, 0),
    },
    Rarity {
        Accessories: (0, 0),
        Aura: (0, 0),
        Body: (0, 3),
        Chest: (0, 4),
        Eyes: (0, 3),
        Hair: (0, 0),
        Horns: (0, 3),
        Mouth: (0, 3),
        Spine: (0, 4),
        Wings: (0, 4),
        Ears: (0, 0),
    },
    Rarity {
        Accessories: (0, 0),
        Aura: (0, 3),
        Body: (0, 2),
        Chest: (0, 3),
        Eyes: (0, 2),
        Hair: (0, 0),
        Horns: (0, 2),
        Mouth: (0, 2),
        Spine: (0, 3),
        Wings: (0, 3),
        Ears: (0, 0),
    },
    Rarity {
        Accessories: (0, 0),
        Aura: (0, 3),
        Body: (0, 2),
        Chest: (0, 3),
        Eyes: (0, 3),
        Hair: (0, 0),
        Horns: (0, 2),
        Mouth: (0, 2),
        Spine: (0, 3),
        Wings: (0, 3),
        Ears: (0, 0),
    },
    Rarity {
        Accessories: (0, 1),
        Aura: (0, 0),
        Body: (0, 1),
        Chest: (0, 2),
        Eyes: (0, 1),
        Hair: (0, 2),
        Horns: (0, 1),
        Mouth: (0, 1),
        Spine: (0, 2),
        Wings: (0, 3),
        Ears: (1, 2),
    },
];
